-- =====================================================================
-- In-app feedback table + screenshots storage bucket
--
-- End users (bakery owners) submit feedback via the floating button.
-- Feedback is global (not multi-tenant) — flows to the super admin in
-- `/feedback`. Discord webhook fires on insert but only receives a
-- minimal payload (category + workspace email + admin link); full
-- content stays in this table and in the private storage bucket.
--
-- Additive only, idempotent. Safe to re-run.
-- =====================================================================

CREATE TABLE IF NOT EXISTS feedback (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  submitted_by        uuid,
  submitted_by_email  text,
  category            text NOT NULL,
  message             text NOT NULL,
  page_url            text,
  language            text,
  user_agent          text,
  screenshot_path     text,
  attachment_path     text,
  status              text NOT NULL DEFAULT 'new',
  created_at          timestamp NOT NULL DEFAULT now(),
  handled_at          timestamp
);

CREATE INDEX IF NOT EXISTS idx_feedback_status     ON feedback(status);
CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON feedback(created_at DESC);

-- RLS: feedback is server-side only. The submit/list/update flows go
-- through tRPC, never directly from the browser via PostgREST.
-- We enable RLS with NO policies so direct anon/authenticated access
-- is blocked. The Drizzle client connects as the database role, which
-- bypasses RLS — that's where all reads/writes happen.
ALTER TABLE feedback ENABLE ROW LEVEL SECURITY;

-- =====================================================================
-- Storage bucket for feedback screenshots
--
-- Private bucket (not publicly readable). Uploads come from the browser
-- using the authenticated user's session; reads happen server-side via
-- signed URLs generated by the admin page.
-- =====================================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('feedback-screenshots', 'feedback-screenshots', false)
ON CONFLICT (id) DO NOTHING;

-- Allow any authenticated user (including anonymous demo users) to upload
-- into their own folder. Path convention: {auth.uid()}/{uuid}.png
DROP POLICY IF EXISTS "feedback_screenshots_insert_own" ON storage.objects;
CREATE POLICY "feedback_screenshots_insert_own"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'feedback-screenshots'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Super admin can read screenshots from their own authenticated session.
-- Keep the email list here in sync with the SUPER_ADMIN_EMAILS env var on
-- the server. To add another admin: append to the ARRAY here AND update
-- the env var in Vercel.
DROP POLICY IF EXISTS "feedback_screenshots_select_superadmin" ON storage.objects;
CREATE POLICY "feedback_screenshots_select_superadmin"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'feedback-screenshots'
    AND EXISTS (
      SELECT 1 FROM auth.users
      WHERE id = auth.uid()
        AND email = ANY(ARRAY['timvdg91@gmail.com'])
    )
  );
